### ISSUE TITLE
XpathOperators

### ISSUE THREAD

**Issue by prpatel723** [tabhresh/Edureka_29thApril#3] opened 2019-05-13 19:19 UTC
package xpathOperators;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

public class Operators {

	public static void main(String[] args) throws InterruptedException {
		
		System.setProperty("webdriver.chrome.driver", "C:\\Program Files\\Selenium\\Installation stuff\\Drivers\\chromedriver.exe");
		WebDriver driver = new ChromeDriver();
		
		driver.get("http://newtours.demoaut.com/");
		
		WebElement text = driver.findElement(By.xpath("//*[contains(text(),'User')"));
		text.getText();
		System.out.println(text);
		
		
		driver.findElement(By.xpath("//input[contains(@name,'userName')]")).sendKeys("abc");
		
		driver.findElement(By.xpath("//*[@type='password' and @name='password']")).sendKeys("er");
		
		driver.findElement(By.xpath("//*[@type='image' or @name='login']")).click();
		driver.navigate().back();	
	}
}

**Comment by AbhreshSugandhi** [comment] 2019-05-14 10:00
The problem is in the closing of brackets..

WebElement text = driver.findElement(By.xpath("//*[contains(text(),'User')]"));
the Xpath structure of brackets are not used properly....
//tagname[contains(text(), 'userName')]

Focus when u get issue try to read what are the response given by eclipse in error lines and console output to..

**Comment by prpatel723** [comment] 2019-05-14 18:23
I added the missing bracket still getting error. I am trying here to find out the use name mentioned in the first page and since it is x-path contains text I don't need to use the complete text so used partial text. Please help me to get the result from that code. And tell me my mistake.

**Comment by AbhreshSugandhi** [comment] 2019-05-15 08:04
I tried to execute but received no errors! Read the error and try to find out what it says and should definitely help you resolve it or if not, do share it here.

**Comment by prpatel723** [comment] 2019-05-17 16:54
package xpathOperators;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

public class Operators {

	public static void main(String[] args) throws InterruptedException {
		
		System.setProperty("webdriver.chrome.driver", "C:\\Program Files\\Selenium\\Installation stuff\\Drivers\\chromedriver.exe");
		WebDriver driver = new ChromeDriver();
		
		//Open site
		driver.get("http://newtours.demoaut.com/");
		
		//Finding text UserName with partial text and x-path
		WebElement text = driver.findElement(By.xpath("//*[contains(text(),'User')]"));
		text.getText();
		System.out.println(text);
		
		//Passing User Name Value
		driver.findElement(By.xpath("//input[contains(@name,'userName')]")).sendKeys("abc");
		
		//Passing password value
		driver.findElement(By.xpath("//*[@type='password' and @name='password']")).sendKeys("er");
		
		//Clicking on Sign-in button
		driver.findElement(By.xpath("//*[@type='image' or @name='login']")).click();
	}
}

**This is the error and it says error in x-path if you can resolve the x-path**
Starting ChromeDriver 2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1) on port 44360
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
May 17, 2019 12:47:08 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
[[ChromeDriver: chrome on XP (f18e12f367ade071f9997b9becdc5b8d)] -> xpath: //*[contains(text(),'User')]]

**Comment by AbhreshSugandhi** [comment] 2019-05-18 07:58
package Issues;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

public class Operators {

public static void main(String[] args) throws InterruptedException {
	
	System.setProperty("webdriver.chrome.driver", "C:\\Program Files\\Selenium\\drivers\\chromedriver_2.46.exe");	
	WebDriver driver = new ChromeDriver();
	
	//Open site
	driver.get("http://newtours.demoaut.com/");
	
	//Finding text UserName with partial text and x-path
	String text = driver.findElement(By.xpath("//*[contains(text(),'User')]")).getText();
	/*
	 * Look at the commands and its description and then use them accordingly
	 * get command is used with String not WebElement 
	 */
	System.out.println(text);

	
	//Passing User Name Value
	driver.findElement(By.xpath("//input[contains(@name,'userName')]")).sendKeys("abc");
	
	//Passing password value
	driver.findElement(By.xpath("//*[@type='password' and @name='password']")).sendKeys("er");
	
	//Clicking on Sign-in button
	driver.findElement(By.xpath("//*[@type='image' or @name='login']")).click();
}
}

**Closed as completed by AbhreshSugandhi** 2019-05-18 07:58 UTC
